### ISSUE TITLE
VS2019 - LNK2005 Error when including raylib-cpp.hpp in multiple files

### ISSUE THREAD

**Issue by AC3Productions** [RobLoach/raylib-cpp#115]
Hello! This is my first time doing something like this on GitHub, so apologies if I'm not familiar with the process/etiquette. 

Currently I'm experiencing an issue with using raylib-cpp in a Visual Studio 2019 project where if I include raylib-cpp.hpp in multiple files (say, main.cpp and some other cpp/header file in the project), I get Linker errors when I try to build:

`LNK2005	"class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl raylib::LoadFileText(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?LoadFileText@raylib@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV23@@Z) already defined in Engine.obj`

`LNK2005	"class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > __cdecl raylib::GetDirectoryFiles(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?GetDirectoryFiles@raylib@@YA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z) already defined in Engine.obj	`

`LNK2005	"class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > __cdecl raylib::GetDroppedFiles(void)" (?GetDroppedFiles@raylib@@YA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@XZ) already defined in Engine.obj`

`LNK1169	one or more multiply defined symbols found`

The only time I can successfully build the project is when the file is included in exactly one cpp file--if I put it in a header and that header is included in multiple files, I get the same errors.

Please let me know if you need more information. Thanks!

**Comment by RobLoach** [comment]
Thanks! Ensuring it works across multiple files is certainly important. Would be good to have an example so we can test accuratlye.

**Comment by RobLoach** [comment]
Thanks! Adding a `static` to the global functions cleans it up a bit. Mind running another test? Thanks!

**Comment by AC3Productions** [comment]
Hey! Sorry for the late response, but it looks like we're all clear on my end--the changes worked and I'm compiling and using the library just fine. Thanks so much!
