### ISSUE TITLE
Should Window class have a Clear() method?

### ISSUE THREAD

**Issue by ufrshubham** [RobLoach/raylib-cpp#125]
Sorry for reporting an issue for this. But I feel that having a Clear() method for Window will make the client side code look more C++ like. Right now I have to call the free floating ClearBackground() from raylib.h or create an object of Color and call ClearBackground() on it. I'll be happy to make the change if everyone wants it.

Also, @RobLoach can you add the Discussion tab for this repo? It will be better to discuss such question there instead of reporting an issue.

**Comment by RobLoach** [comment]
`Clear()` for the Window is a great idea! Feel free to either submit the pull request, or I can get to it sometime this week 😉 

Just enabled the Discussions. Never used then, so happy to get peoples ideas on where it could go. Thanks for the suggestion!

**Comment by RobLoach** [comment]
Thanks so much for this! Cleans it up a lot.

**Comment by ufrshubham** [comment]
Sure, I'll keep that in mind for next PRs.

**Comment by ufrshubham** [comment]
#127 closes this issue.
