### ISSUE TITLE
Build error while compiling the examples with raylib-cpp

### ISSUE THREAD

**Issue by goksanisil23** [RobLoach/raylib-cpp#129]
Hi,

Thanks for providing this cpp wrapper for raylib.

I'm getting the following build errors during "make" stage:

`Scanning dependencies of target multiple
[  2%] Building CXX object examples/CMakeFiles/multiple.dir/multiple/main.cpp.o
In file included from /home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:5:0,
                 from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:38,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/././Vector3.hpp: In member function ‘raylib::Vector3& raylib::Vector3::DrawGizmo()’:
/home/goksan/Downloads/raylib-cpp/include/././Vector3.hpp:295:11: error: ‘::DrawGizmo’ has not been declared
         ::DrawGizmo(*this);
           ^~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/././Vector3.hpp:295:11: note: suggested alternative: ‘DrawGrid’
         ::DrawGizmo(*this);
           ^~~~~~~~~
           DrawGrid
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:38:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp: In constructor ‘raylib::Camera3D::Camera3D(Vector3, Vector3, Vector3, float, int)’:
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:24:9: error: ‘type’ was not declared in this scope
         type = typeValue;
         ^~~~
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:24:9: note: suggested alternative: ‘GetType’
         type = typeValue;
         ^~~~
         GetType
In file included from /home/goksan/Downloads/raylib-cpp/include/./AudioDevice.hpp:5:0,
                 from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:34,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp: In member function ‘int raylib::Camera3D::GetType() const’:
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:33:29: error: ‘type’ was not declared in this scope
     GETTERSETTER(int, Type, type)
                             ^
/home/goksan/Downloads/raylib-cpp/include/././raylib-cpp-utils.hpp:17:46: note: in definition of macro ‘GETTERSETTER’
     inline type Get##method() const { return name; }  \
                                              ^~~~
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:33:29: note: suggested alternative: ‘GetType’
     GETTERSETTER(int, Type, type)
                             ^
/home/goksan/Downloads/raylib-cpp/include/././raylib-cpp-utils.hpp:17:46: note: in definition of macro ‘GETTERSETTER’
     inline type Get##method() const { return name; }  \
                                              ^~~~
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp: In member function ‘void raylib::Camera3D::SetType(int)’:
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:33:29: error: ‘type’ was not declared in this scope
     GETTERSETTER(int, Type, type)
                             ^
/home/goksan/Downloads/raylib-cpp/include/././raylib-cpp-utils.hpp:19:43: note: in definition of macro ‘GETTERSETTER’
     inline void Set##method(type value) { name = value; }
                                           ^~~~
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:33:29: note: suggested alternative: ‘GetType’
     GETTERSETTER(int, Type, type)
                             ^
/home/goksan/Downloads/raylib-cpp/include/././raylib-cpp-utils.hpp:19:43: note: in definition of macro ‘GETTERSETTER’
     inline void Set##method(type value) { name = value; }
                                           ^~~~
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:38:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp: In member function ‘void raylib::Camera3D::set(const Camera3D&)’:
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:159:9: error: ‘type’ was not declared in this scope
         type = camera.type;
         ^~~~
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:159:9: note: suggested alternative: ‘GetType’
         type = camera.type;
         ^~~~
         GetType
/home/goksan/Downloads/raylib-cpp/include/./Camera3D.hpp:159:23: error: ‘const Camera3D {aka const struct Camera3D}’ has no member named ‘type’
         type = camera.type;
                       ^~~~
In file included from /home/goksan/Downloads/raylib-cpp/include/./AudioDevice.hpp:5:0,
                 from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:34,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Material.hpp: In member function ‘float* raylib::Material::GetParams() const’:
/home/goksan/Downloads/raylib-cpp/include/./Material.hpp:42:34: error: invalid conversion from ‘const float*’ to ‘float*’ [-fpermissive]
     GETTERSETTER(float*, Params, params)
                                  ^
/home/goksan/Downloads/raylib-cpp/include/././raylib-cpp-utils.hpp:17:46: note: in definition of macro ‘GETTERSETTER’
     inline type Get##method() const { return name; }  \
                                              ^~~~
/home/goksan/Downloads/raylib-cpp/include/./Material.hpp: In member function ‘void raylib::Material::SetParams(float*)’:
/home/goksan/Downloads/raylib-cpp/include/././raylib-cpp-utils.hpp:19:50: error: incompatible types in assignment of ‘float*’ to ‘float [4]’
     inline void Set##method(type value) { name = value; }
                                                  ^
/home/goksan/Downloads/raylib-cpp/include/./Material.hpp:42:5: note: in expansion of macro ‘GETTERSETTER’
     GETTERSETTER(float*, Params, params)
     ^~~~~~~~~~~~
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:44:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Material.hpp: In member function ‘void raylib::Material::set(const Material&)’:
/home/goksan/Downloads/raylib-cpp/include/./Material.hpp:71:27: error: invalid array assignment
         params = material.params;
                           ^~~~~~
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:45:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp: In member function ‘raylib::Matrix& raylib::Matrix::SetProjection()’:
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:93:11: error: ‘::SetMatrixProjection’ has not been declared
         ::SetMatrixProjection(*this);
           ^~~~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:93:11: note: suggested alternative: ‘SetProjection’
         ::SetMatrixProjection(*this);
           ^~~~~~~~~~~~~~~~~~~
           SetProjection
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp: In member function ‘raylib::Matrix& raylib::Matrix::SetModelview()’:
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:101:11: error: ‘::SetMatrixModelview’ has not been declared
         ::SetMatrixModelview(*this);
           ^~~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:101:11: note: suggested alternative: ‘SetModelview’
         ::SetMatrixModelview(*this);
           ^~~~~~~~~~~~~~~~~~
           SetModelview
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp: In static member function ‘static raylib::Matrix raylib::Matrix::GetModelview()’:
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:109:18: error: ‘::GetMatrixModelview’ has not been declared
         return ::GetMatrixModelview();
                  ^~~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:109:18: note: suggested alternative: ‘GetModelview’
         return ::GetMatrixModelview();
                  ^~~~~~~~~~~~~~~~~~
                  GetModelview
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp: In static member function ‘static raylib::Matrix raylib::Matrix::GetProjection()’:
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:116:18: error: ‘::GetMatrixProjection’ has not been declared
         return ::GetMatrixProjection();
                  ^~~~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Matrix.hpp:116:18: note: suggested alternative: ‘GetProjection’
         return ::GetMatrixProjection();
                  ^~~~~~~~~~~~~~~~~~~
                  GetProjection
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:46:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Mesh.hpp: In static member function ‘static std::vector<raylib::Mesh> raylib::Mesh::Load(const string&)’:
/home/goksan/Downloads/raylib-cpp/include/./Mesh.hpp:32:26: error: ‘LoadMeshes’ was not declared in this scope
         ::Mesh* meshes = LoadMeshes(fileName.c_str(), &count);
                          ^~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Mesh.hpp:32:26: note: suggested alternative: ‘LoadModel’
         ::Mesh* meshes = LoadMeshes(fileName.c_str(), &count);
                          ^~~~~~~~~~
                          LoadModel
/home/goksan/Downloads/raylib-cpp/include/./Mesh.hpp: In member function ‘raylib::Mesh& raylib::Mesh::NormalsSmooth()’:
/home/goksan/Downloads/raylib-cpp/include/./Mesh.hpp:183:11: error: ‘::MeshNormalsSmooth’ has not been declared
         ::MeshNormalsSmooth(this);
           ^~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Mesh.hpp:183:11: note: suggested alternative: ‘NormalsSmooth’
         ::MeshNormalsSmooth(this);
           ^~~~~~~~~~~~~~~~~
           NormalsSmooth
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:49:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Mouse.hpp: In static member function ‘static int raylib::Mouse::GetCursor()’:
/home/goksan/Downloads/raylib-cpp/include/./Mouse.hpp:75:18: error: ‘::GetMouseCursor’ has not been declared
         return ::GetMouseCursor();
                  ^~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Mouse.hpp:75:18: note: suggested alternative: ‘SetMouseCursor’
         return ::GetMouseCursor();
                  ^~~~~~~~~~~~~~
                  SetMouseCursor
In file included from /home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:8:0,
                 from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:55,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Texture.hpp: In constructor ‘raylib::Texture::Texture()’:
/home/goksan/Downloads/raylib-cpp/include/./Texture.hpp:22:15: error: ‘::GetTextureDefault’ has not been declared
         set(::GetTextureDefault());
               ^~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Texture.hpp:22:15: note: suggested alternative: ‘GetTextureData’
         set(::GetTextureDefault());
               ^~~~~~~~~~~~~~~~~
               GetTextureData
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:55:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp: In constructor ‘raylib::Shader::Shader()’:
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:26:13: error: ‘GetShaderDefault’ was not declared in this scope
         set(GetShaderDefault());
             ^~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:26:13: note: suggested alternative: ‘GetFontDefault’
         set(GetShaderDefault());
             ^~~~~~~~~~~~~~~~
             GetFontDefault
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp: In static member function ‘static Shader raylib::Shader::LoadCode(const string&, const string&)’:
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:44:18: error: ‘::LoadShaderCode’ has not been declared
         return ::LoadShaderCode(vsCode.c_str(), fsCode.c_str());
                  ^~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:44:18: note: suggested alternative: ‘LoadShader’
         return ::LoadShaderCode(vsCode.c_str(), fsCode.c_str());
                  ^~~~~~~~~~~~~~
                  LoadShader
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp: In member function ‘TextureCubemap raylib::Shader::GenTextureCubemap(const Texture2D&, int, int) const’:
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:138:18: error: ‘::GenTextureCubemap’ has not been declared
         return ::GenTextureCubemap(*this, panorama, size, format);
                  ^~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:138:18: note: suggested alternative: ‘TextureCubemap’
         return ::GenTextureCubemap(*this, panorama, size, format);
                  ^~~~~~~~~~~~~~~~~
                  TextureCubemap
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp: In member function ‘TextureCubemap raylib::Shader::GenTextureIrradiance(const Texture2D&, int) const’:
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:142:18: error: ‘::GenTextureIrradiance’ has not been declared
         return ::GenTextureIrradiance(*this, panorama, size);
                  ^~~~~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:142:18: note: suggested alternative: ‘GenTextureMipmaps’
         return ::GenTextureIrradiance(*this, panorama, size);
                  ^~~~~~~~~~~~~~~~~~~~
                  GenTextureMipmaps
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp: In member function ‘TextureCubemap raylib::Shader::GenTexturePrefilter(const Texture2D&, int) const’:
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:146:18: error: ‘::GenTexturePrefilter’ has not been declared
         return ::GenTexturePrefilter(*this, panorama, size);
                  ^~~~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:146:18: note: suggested alternative: ‘SetTextureFilter’
         return ::GenTexturePrefilter(*this, panorama, size);
                  ^~~~~~~~~~~~~~~~~~~
                  SetTextureFilter
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp: In member function ‘Texture2D raylib::Shader::GenTextureBRDF(int) const’:
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:150:18: error: ‘::GenTextureBRDF’ has not been declared
         return ::GenTextureBRDF(*this, size);
                  ^~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./Shader.hpp:150:18: note: suggested alternative: ‘GetTextureData’
         return ::GenTextureBRDF(*this, size);
                  ^~~~~~~~~~~~~~
                  GetTextureData
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:62:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp: In member function ‘void raylib::VrSimulator::Init()’:
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp:26:25: error: too few arguments to function ‘void InitVrSimulator(VrDeviceInfo)’
         InitVrSimulator();
                         ^
In file included from /home/goksan/Downloads/raylib-cpp/include/././raylib.hpp:10:0,
                 from /home/goksan/Downloads/raylib-cpp/include/./AudioDevice.hpp:4,
                 from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:34,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/usr/local/include/raylib.h:1102:12: note: declared here
 RLAPI void InitVrSimulator(VrDeviceInfo device);        // Init VR simulator for selected device parameters
            ^~~~~~~~~~~~~~~
In file included from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:62:0,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp: In member function ‘raylib::VrSimulator& raylib::VrSimulator::Set(VrDeviceInfo, Shader)’:
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp:64:11: error: ‘::SetVrConfiguration’ has not been declared
         ::SetVrConfiguration(info, distortion);
           ^~~~~~~~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp:64:11: note: suggested alternative: ‘GetVrConfig’
         ::SetVrConfiguration(info, distortion);
           ^~~~~~~~~~~~~~~~~~
           GetVrConfig
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp: In member function ‘raylib::VrSimulator& raylib::VrSimulator::Toggle()’:
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp:72:11: error: ‘::ToggleVrMode’ has not been declared
         ::ToggleVrMode();
           ^~~~~~~~~~~~
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp:72:11: note: suggested alternative: ‘Toggle’
         ::ToggleVrMode();
           ^~~~~~~~~~~~
           Toggle
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp: In member function ‘raylib::VrSimulator& raylib::VrSimulator::BeginDrawing()’:
/home/goksan/Downloads/raylib-cpp/include/./VrSimulator.hpp:80:26: error: too few arguments to function ‘void BeginVrDrawing(RenderTexture2D)’
         ::BeginVrDrawing();
                          ^
In file included from /home/goksan/Downloads/raylib-cpp/include/././raylib.hpp:10:0,
                 from /home/goksan/Downloads/raylib-cpp/include/./AudioDevice.hpp:4,
                 from /home/goksan/Downloads/raylib-cpp/include/raylib-cpp.hpp:34,
                 from /home/goksan/Downloads/raylib-cpp/examples/multiple/main.cpp:1:
/usr/local/include/raylib.h:1106:12: note: declared here
 RLAPI void BeginVrDrawing(RenderTexture2D target);      // Begin VR simulator stereo rendering (using provided fbo)
            ^~~~~~~~~~~~~~
examples/CMakeFiles/multiple.dir/build.make:62: recipe for target 'examples/CMakeFiles/multiple.dir/multiple/main.cpp.o' failed
make[2]: *** [examples/CMakeFiles/multiple.dir/multiple/main.cpp.o] Error 1
CMakeFiles/Makefile2:1044: recipe for target 'examples/CMakeFiles/multiple.dir/all' failed
make[1]: *** [examples/CMakeFiles/multiple.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

Am I missing something here?

Thanks in advance

**Comment by RobLoach** [comment]
: ‘::GenTextureBRDF’ has not been declared return ::GenTextureBRDF(*this, size); ^

makes me think that raylib wasn't found. Have you built raylib before?

**Comment by goksanisil23** [comment]
Hi,

Yes the problem was due to having the latest version of the raylib installed in the system path.

**Comment by RobLoach** [comment]
Ah, nice find! I've created a next branch which targets raylib master. Could likely do with an update!
