### ISSUE TITLE
VS2019 - Project builds and runs raylib, but does not build raylib-cpp.

### ISSUE THREAD

**Issue by AC3Productions** [RobLoach/raylib-cpp#130]
Raylib is working fine in a solution I've set up, but after adding raylib-cpp's include directory to my project, I get the following errors: [raylib-cpp_errors.txt](https://github.com/RobLoach/raylib-cpp/files/6373038/raylib-cpp_errors.txt)

These errors show up when I include `raylib-cpp.hpp`. I'm fairly certain I have raylib set up properly; if I run some raylib sample code and include `raylib.h` instead, it works as intended. Here is a small test project, using version 3.5.0 of both raylib and raylib-cpp, which produces the same errors:  [test_project.zip](https://github.com/RobLoach/raylib-cpp/files/6373067/test_project.zip)

I _believe_ they're both properly set up, but it's possible (and I think likely) that I've done something wrong. It was working at one point a few months ago (once #115 was resolved), but since then I've been very busy, and I recently moved the project to a new machine, so something has changed and I'm not sure what's causing the issue.

I want to also note that this situation looks similar to a recent issue someone else posted (#129), but I don't believe I've done anything like putting raylib in the path. However, I do think it could be something related to which versions of raylib and raylib-cpp I'm using, not sure.

**Comment by RobLoach** [comment]
Looks like you might be using an incorrect version of raylib? Try using 3.7.0... Was just merged in! :rocket:

**Comment by AC3Productions** [comment]
Right you are! Thank you so much!

**Comment by RobLoach** [comment]
Let me know if you run into troubles iwth the VS project files. I don't use VS, so definitely would appreciate the help keeping them up to date :+1:
