### ISSUE TITLE
Includes of raylib-cpp.hpp generate warnings for "unused-function"

### ISSUE THREAD

**Issue by J-Mo63** [RobLoach/raylib-cpp#134]
Hi @RobLoach. I've recently repointed my submodule for `raylib-cpp` to latest and I've noticed that the include of `raylib-cpp.hpp` will generate three compiler warnings for each include statement in reference to the functions `LoadFileText` `GetDirectoryFiles` and `GetDroppedFiles` as below:

<img width="923" alt="Screen Shot 2021-07-18 at 1 56 18 pm" src="https://user-images.githubusercontent.com/9414994/126147312-311e73ca-8187-4091-bebc-c5cffd7d9844.png">

The issue can be solved quite trivially by applying the `[[maybe_unused]]` hint to either the beginning of the function declaration, or just above as so:

```c++
[[maybe_unused]]
RLCPPAPI std::string LoadFileText(const std::string& fileName) {
    char* text = ::LoadFileText(fileName.c_str());
    std::string output(text);
    ::UnloadFileText((unsigned char*)text);
    return output;
}

[[maybe_unused]]
RLCPPAPI std::vector<std::string> GetDirectoryFiles(const std::string& dirPath) {
    int count;
    char** files = ::GetDirectoryFiles(dirPath.c_str(), &count);
    std::vector<std::string> output(files, files + count);
    ::ClearDirectoryFiles();
    return output;
}

[[maybe_unused]]
RLCPPAPI std::vector<std::string> GetDroppedFiles() {
    if (!::IsFileDropped()) {
        return std::vector<std::string>();
    }
    int count;
    char** files = ::GetDroppedFiles(&count);
    std::vector<std::string> output(files, files + count);
    ::ClearDroppedFiles();
    return output;
}
```

Let me know your thoughts and I can put in a PR for it!

**Comment by RobLoach** [comment]
Thanks! Looks like a simple addition. Strange that it issues warnings for those. They are used in the examples :shrug:

**Comment by J-Mo63** [comment]
Perhaps CMake doesn't have `-Wall` on by default? Either way, I'll submit a PR for it.

**Comment by RobLoach** [comment]
Thanks for the fix up!
