### ISSUE TITLE
class Sound does not implement copy ctor properly

### ISSUE THREAD

**Issue by maciejewiczow** [RobLoach/raylib-cpp#137]
Copying a Sound object does not copy the rAudioBuffer of AudioStream from the parent class. Multiple copies of one sound instance getting destroyed causes then a double-free error on the buffer (since they all share the same buffer).

**Comment by maciejewiczow** [comment]
After digging around in raylib for a while I realised that copying a Sound struct is not that easy, so the copy ctor/assigmnent should be marked as deleted.

**Comment by RobLoach** [comment]
Is that this one?

```
    Sound(const ::Sound& vec) {
        set(vec);
    }
```

**Comment by maciejewiczow** [comment]
That would not work, because in the constructor you're trying to modify the other sound object which is marked as const. Imo the best solution is to delete the copy operators, because raylib does not provide a mechanism to copy a sound struct (as far as I know). 
Something like this
```cpp
    Sound(const Sound&) = delete;
    Sound& operator=(const Sound&) = delete;

    Sound(Sound&& other) {
        set(other);

        other.sampleCount = 0;
        other.stream = { 0 };
    };

    Sound& operator=(Sound&& other) {
        if (this == &other)
            return *this;

        Unload();
        set(other);
        other.sampleCount = 0;
        other.stream = { 0 };

        return *this;
    };

    ~Sound() {
        Unload();
    }
```
I also added proper move ctro/assigmnent, because the default one also caused memory errors.
I can make a PR if you want

**Comment by RobLoach** [comment]
Oh, that's pretty cool. A test of it would be awesome too. Something simple would be enough.

**Comment by maciejewiczow** [comment]
I think that #102 is a symptom of the same problem that I encountered here surfacing in the other classes.
