### ISSUE TITLE
CTestCustom.cmake does not exist

### ISSUE THREAD

**Issue by omrisim210** [RobLoach/raylib-cpp#15]
Hi, I'm trying to set up a project using the suggested cmake file.
I used the exact same one in `projects/CMake` (apart from trivial modifications like the project name) and I get the following error when I run `cd build; cmake ..`:

```
CMake Error: File /home/user/code/myproject/cmake/CTestCustom.cmake does not exist.
CMake Error at /tmp/cmakeCVUo5k/_deps/raylib-cpp-src/CMakeLists.txt:8 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
See also "/tmp/cmakeCVUo5k/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:176: cmake_check_build_system] Error 1
```

It seems like `CMAKE_SOURCE_DIR` is set to my project's root directory instead of raylib-cpp's when this line runs:

https://github.com/RobLoach/raylib-cpp/blob/06ac6fa4fcc29b0937f074276a0ed95d95691011/CMakeLists.txt#L8

I'm not very experienced with cmake so I don't know too much beyond what I've shown here.

**Comment by RobLoach** [comment]
We don't need that file. Thanks for finding this one!!!

**Comment by RobLoach** [comment]
Updated the CMake example project a bit. Seems to be working again... Thanks a lot!

Also, been looking around for more useful examples of getting it up and running. If you think of any, let me know.
