### ISSUE TITLE
Unexpected Vector2 operator behaviour

### ISSUE THREAD

**Issue by Ralayax** [RobLoach/raylib-cpp#155]
Hi,

It seems like operators on Vector2 modify the base object instead of making a copy.

```cpp
raylib::Vector2 size{50,50};
raylib::Vector2 halfsize = size/2.0f;

std::cout << size.x << '\n';
std::cout << halfsize.x << '\n';
```

`
25
25
`

operator/ probably shoudn't modify the underlying object and be marked as const.

Merry christmas

**Comment by RobLoach** [comment]
Good find! 👍

**Comment by RobLoach** [comment]
Fixed in https://github.com/RobLoach/raylib-cpp/commit/9de4e175e429f5fcfeea1fd839f14a31d060fd75 ... THanks a lot!
