### ISSUE TITLE
Using raylib::TextSubtext results in an Address boundary error

### ISSUE THREAD

**Issue by spiwocoal** [RobLoach/raylib-cpp#158]
Hey! While developing a simple game using this (and its parent) library I ran into an Address boundary error that seems to originate from the `raylib::TextSubtext` function. This only happens when I call the `raylib-cpp` binding of the function, as using the original function from `raylib` works as intended.

For a bit of context, I am trying to build the [logo screen](https://github.com/raysan5/raylib-game-template/blob/main/src/screen_logo.c) that is in the [raylib-game-template](https://github.com/raysan5/raylib-game-template) repo, but in C++ using this library for bindings. One of the steps of this screen consists of drawing letter-by-letter the word "raylib". The drawing part of this looks like this (with `lettersCount` being incremented after a defined number of frames and `alpha` a float slowly decreasing from `1.0f` to `0.0f`):
```c
DrawText(TextSubtext("raylib", 0, lettersCount), GetScreenWidth()/2 - 44, GetScreenHeight()/2 + 48, 50, Fade(BLACK, alpha));
```

I wrote this in C++ like so:
```cpp
rayilb::Color::Black.Fade(alpha).DrawText(raylib::TextSubtext("raylib", 0, lettersCount), (window.GetWidth() / 2) - 44, window.GetHeight() / 2) + 48, 50);
```

But when I try running it, once the program reaches that instruction, it crashes with a `SIGSEV`, indicating an Address boundary error.

My guess is that this is caused by some sort of caveat related to the way `std::string.c_str()` works as this is what is used by the binding, but I lack the knowledge to precisely know what the problem really is.

For the moment I'll just use the base library's `TextSubtext`, but I though reporting this behavior would be useful.

BTW, this happend under Arch Linux running kernel version `5.16.0`, and compiled using `g++` version `11.1.0` and `C++17`.

> As a little side note, shouldn't the documentation for `raylib::TextSubtext` be something along the lines of `Get a piece of a text string` instead of `Get text length, checks for '\0' ending`?

**Comment by RobLoach** [comment]
Good find! Looks like the memory is expected to be freed in some of these functions. We may want to clean them up a bit.
