### ISSUE TITLE
Invalid texture path silently fails

### ISSUE THREAD

**Issue by NobleOMD** [RobLoach/raylib-cpp#160]
If we have:
```cpp
raylib::Texture texture{"somePath/mytexture.png"}
````
And `"somePath/mytexture.png"` does not exist the initialisation will silently fail leaving a blank texture. Prehaps an assertion like so would fix this:

```cpp
// Texture.hpp
class Texture : public ::Texture {
...
    Texture(const std::string& fileName) {
        assert(raylib::FileExists(fileName)); // If assertion triggers: file does not exist
        Load(fileName);
    }
...
}
```
I was wondering if there would be any reason not to do this, as this is what I have done to the header file in my project

**Comment by RobLoach** [comment]
Very true... Have been considering throwing some Exceptions when things fail to load. I implemented a [`IsLoaded()` function for Image](https://github.com/RobLoach/raylib-cpp/blob/master/include/Image.hpp#L621-L628). Could implement some other similar functions across hte objects too.

**Comment by NobleOMD** [comment]
I think that your width check is probably better than checking the file system. I will implement that in my header file instead and come back if there are issues with that solution.

**Comment by NobleOMD** [comment]
A few hours later and I have found an issue with having the assertion in the `Texture` class. I have an object which has a Texture as a variable. If I want to instantiate it without the texture it will throw because I haven't given a texture. I think that this "Has the Texture been loaded?" check should be in my constructor for the object rather than in the Texture class iteslf.

**Comment by RobLoach** [comment]
That's a good point. Would be good to check in the constructor... Also, considering there is a `IsAudioDeviceReady()` and `IsWindowReady()`, may be worth having the methods be called `IsReady()`.

``` c
Texture texture("image.png");
texture.IsReady();
```

Within the constructor itself, how do you think we should throw the exception? Should it be called `RaylibException`?

**Comment by RobLoach** [comment]
Going to continue concersation in the Exceptions PR! Thanks so much :wink:

**Comment by RobLoach** [comment]
> At the moment there isn't a default constructor for the Texture objects (and I think most others) however I think this would be the best solution. We would still get an error if we tried to draw the Texture before giving it an image to draw and also won't have to manually search the game for the error texture.

One thing you may want to try is having an initializer list for each constructor, giving you more control on how the Texture is loaded:
https://en.cppreference.com/w/cpp/language/constructor

Rather than ALWYAS constructing it with the string, this would let you change it to the X/Y/Color one if needed.

**Comment by NobleOMD** [comment]
> One thing you may want to try is having an initializer list for each constructor

This is how I am currently doing it (I just didn't include the .cpp part of the class before):

```cpp
// gameObject.hpp
...
enum drawStates { fill, outline, texture };

class GameObject {
protected:
	...
	int drawState;
	raylib::Color objectColour;
	raylib::Texture texture;
	...
public:
	GameObject(raylib::Vector2 size, raylib::Vector2 position, raylib::Color colour);
	GameObject(raylib::Vector2 size, raylib::Vector2 position, std::string textureFileName);
	...

// gameObject.cpp
#include gameObject.hpp
...
GameObject::GameObject(raylib::Vector2 size, raylib::Vector2 position, raylib::Color colour, drawStates drawState)
	:
	size(size),
	gridPosition(position),
	entityColour(colour),
	drawState(drawState)
{}

GameObject::GameObject(raylib::Vector2 size, raylib::Vector2 position, std::string textureFileName, raylib::Vector2 texturePos)
	:
	size(size),
	gridPosition(position),
	entityTextures(raylib::Texture(textureFileName)),
	texturePos(texturePos),
	drawState(drawStates::texture)
{}
...
```
Not sure if those initialiser lists could be improved but it works.
