### ISSUE TITLE
Doxygen theme

### ISSUE THREAD

**Issue by raynei86** [RobLoach/raylib-cpp#189]
The documentation theme can really use some work, perhaps something like [m.css](https://mcss.mosra.cz)?

**Comment by RobLoach** [comment]
Certainly open to changing the theme for doxygen, as long as it's easy to implement and requires minimal maintenance.

**Comment by raynei86** [comment]
I've made some changes in [in my own fork](https://github.com/raynei86/raylib-cpp). I couldn't really get m.css working, so I opted for [doxygen awesome theme](https://github.com/jothepro/doxygen-awesome-css) instead. I'll make a PR if satisfactory.

**Comment by RobLoach** [comment]
Thanks so much, looks like a great option.

**Comment by raynei86** [comment]
No problem! I'll make the PR now.
