### ISSUE TITLE
Simplify raylib-cpp

### ISSUE THREAD

**Issue by TokyoSU** [RobLoach/raylib-cpp#199]
I think writing `raylib::` for each think is pretty anoying, so ive done a workaround to simplify it:
```
// add more when a new release appear !

using RWindow = raylib::Window;
using RVector2 = raylib::Vector2;
using RVector3 = raylib::Vector3;
using RCamera = raylib::Camera;
using RCamera2D = raylib::Camera2D;
using RCamera3D = raylib::Camera3D;
using RColor = raylib::Color;
using RTexture = raylib::Texture;
using RRenderTexture = raylib::RenderTexture;
using RRenderTexture2D = raylib::RenderTexture2D;
using RShader = raylib::Shader;
using RModel = raylib::Model;
using RModelAnimation = raylib::ModelAnimation;
```
this will maintain the code clean, maybe doing a simple .hpp or .h to include it after `raylib-cpp.hpp` by default could be great, else i will do with this one :x

**Comment by RobLoach** [comment]
That seems like a great workaround. Do you think we should have a RAYLIB_CPP_SHORTHAND define or something to ease inclusion? Or a raylib-cpp-shorthand.hpp or something?

**Comment by TokyoSU** [comment]
A simple define will do :)

**Comment by RobLoach** [comment]
I think we could simply skips the define, and include the alias in each file right after the class definition... Maybe? Would you be willing the submit the PR?

**Comment by TokyoSU** [comment]
ive done this work on the import from my project not directly from the git.
but its something simple, it will be done fast, okay no problem :)

**Comment by TokyoSU** [comment]
Pull request send :)

**Comment by RobLoach** [comment]
Nicely done! Happy to have this in :+1:
