### ISSUE TITLE
Cannot use raylib-cpp.hpp 

### ISSUE THREAD

**Issue by bipul018** [RobLoach/raylib-cpp#200]
When including raylib-cpp.hpp during compilation it says error global namespace has no "GetDirectoryFiles" and "ClearDirectoryFiles" and such other . Is this because of raylib version mismatch?

**Comment by RobLoach** [comment]
Which version of raylib are you using? This targets 4.0.0 right now.

**Comment by bipul018** [comment]
I just cloned master repo of raylib

**Comment by bipul018** [comment]
Oh, ok, so I have to use 4.0.0 tag of raylib

**Comment by RobLoach** [comment]
It does need an update to the latest.
