### ISSUE TITLE
Update to raylib 4.2

### ISSUE THREAD

**Issue by Ismaw34** [RobLoach/raylib-cpp#206]
Hello,
I think you know this already but, the wrapper does not work on the released 4.2 raylib.
I think is being worked on https://github.com/RobLoach/raylib-cpp/pull/188 but i dont know if you are aware of this.
Thanks.

**Comment by RobLoach** [comment]
Thanks so much for making the issue for it! :+1:

**Comment by RobLoach** [comment]
We'll have to decide if this would be raylib-cpp 4.2.5, or raylib-cpp 5.0 :thinking:

**Comment by Ismaw34** [comment]
Just put 4.2.5, is for 4.2 and wrapper version for that version is 5.
