### ISSUE TITLE
Object Pointer Classes that don't Unload

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/raylib-cpp#213]
When a parent object returns a child object, the child object will destroy itself. We should have a way to have the C++ wrappers in place without the child object inadvertantly destroying itself.

```cpp
raylib::Font font("myfont.ttf");
{
  raylib::Texture fontTexture = font.GetTexture();
  fontTexture.Draw();
}
// Error: The font.texture will be destroyed since the context is garbage collected above.
```

**Comment by Ataraxia-Mechanica** [comment]
Just discovered there's a way to retrieve child objects that don't destroy itself when out of scope, but it's quite hacky since it involves type punning : `((rl::Texture&)render_texture.texture).Draw(from, to);`.
