### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by AbhayAysola** [RobLoach/raylib-cpp#227]
I followed the instructions in the README but I can't seem to get it to compile
Sorry if this is a basic issue on my part

Here's the error output
```ninja: Entering directory `/home/abhay/Desktop/bitsim/build'
[1/2] Compiling C++ object bitsim.p/bitsim.cpp.o
FAILED: bitsim.p/bitsim.cpp.o
c++ -Ibitsim.p -I. -I.. -I../raylib-cpp/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++14 -O0 -g -MD -MQ bitsim.p/bitsim.cpp.o -MF bitsim.p/bitsim.cpp.o.d -o bitsim.p/bitsim.cpp.o -c ../bitsim.cpp
In file included from ../raylib-cpp/include/./Camera3D.hpp:5,
                 from ../raylib-cpp/include/raylib-cpp.hpp:38,
                 from ../bitsim.cpp:2:
../raylib-cpp/include/././Vector3.hpp: In member function ‘void raylib::Vector3::DrawCubeTexture(const Texture2D&, float, float, float, Color) const’:
../raylib-cpp/include/././Vector3.hpp:305:11: error: ‘::DrawCubeTexture’ has not been declared; did you mean ‘DrawTexture’?
  305 |         ::DrawCubeTexture(texture, *this, width, height, length, color);
      |           ^~~~~~~~~~~~~~~
      |           DrawTexture
In file included from ../raylib-cpp/include/./Font.hpp:9,
                 from ../raylib-cpp/include/raylib-cpp.hpp:40:
../raylib-cpp/include/././TextureUnmanaged.hpp: In member function ‘void raylib::TextureUnmanaged::Draw(Vector2, Vector2, Rectangle, Color) const’:
../raylib-cpp/include/././TextureUnmanaged.hpp:241:11: error: ‘::DrawTextureQuad’ has not been declared; did you mean ‘DrawTexture ’?
  241 |         ::DrawTextureQuad(*this, tiling, offset, quad, tint);
      |           ^~~~~~~~~~~~~~~
      |           DrawTextureV
../raylib-cpp/include/././TextureUnmanaged.hpp: In member function ‘void raylib::TextureUnmanaged::DrawTiled(Rectangle, Rectangle, Vector2, float, float, raylib::Color) const’:
../raylib-cpp/include/././TextureUnmanaged.hpp:271:11: error: ‘::DrawTextureTiled’ has not been declared; did you mean ‘DrawTextureRec’?
  271 |         ::DrawTextureTiled(*this, sourceRec, destRec, origin, rotation, scale, tint);
      |           ^~~~~~~~~~~~~~~~
      |           DrawTextureRec
../raylib-cpp/include/././TextureUnmanaged.hpp: In member function ‘void raylib::TextureUnmanaged::DrawPoly(Vector2, Vector2*, Vector2*, int, Color) const’:
../raylib-cpp/include/././TextureUnmanaged.hpp:282:11: error: ‘::DrawTexturePoly’ has not been declared; did you mean ‘DrawTexturePro’?
  282 |         ::DrawTexturePoly(*this, center, points, texcoords, pointsCount, tint);
      |           ^~~~~~~~~~~~~~~
      |           DrawTexturePro
../raylib-cpp/include/././TextureUnmanaged.hpp: In member function ‘void raylib::TextureUnmanaged::DrawCube(Vector3, float, float, float, Color) const’:
../raylib-cpp/include/././TextureUnmanaged.hpp:326:11: error: ‘::DrawCubeTexture’ has not been declared; did you mean ‘DrawTexture’?
  326 |         ::DrawCubeTexture(*this, position, width, height, length, color);
      |           ^~~~~~~~~~~~~~~
      |           DrawTexture
../raylib-cpp/include/././TextureUnmanaged.hpp: In member function ‘void raylib::TextureUnmanaged::DrawCube(Vector3, Vector3, Color) const’:
../raylib-cpp/include/././TextureUnmanaged.hpp:336:11: error: ‘::DrawCubeTexture’ has not been declared; did you mean ‘DrawTexture’?
  336 |         ::DrawCubeTexture(*this, position, dimensions.x, dimensions.y, dimensions.z, color);
      |           ^~~~~~~~~~~~~~~
      |           DrawTexture
../raylib-cpp/include/././TextureUnmanaged.hpp: In member function ‘void raylib::TextureUnmanaged::DrawCube(Rectangle, Vector3, float, float, float, Color) const’:
../raylib-cpp/include/././TextureUnmanaged.hpp:346:11: error: ‘::DrawCubeTextureRec’ has not been declared; did you mean ‘DrawTextureRec’?
  346 |         ::DrawCubeTextureRec(*this, source, position, width, height, length, color);
      |           ^~~~~~~~~~~~~~~~~~
      |           DrawTextureRec
../raylib-cpp/include/././TextureUnmanaged.hpp: In member function ‘void raylib::TextureUnmanaged::DrawCube(Rectangle, Vector3, Vector3, Color) const’:
../raylib-cpp/include/././TextureUnmanaged.hpp:356:11: error: ‘::DrawCubeTextureRec’ has not been declared; did you mean ‘DrawTextureRec’?
  356 |         ::DrawCubeTextureRec(*this, source, position, dimensions.x, dimensions.y, dimensions.z, color);
      |           ^~~~~~~~~~~~~~~~~~
      |           DrawTextureRec
In file included from ../raylib-cpp/include/raylib-cpp.hpp:41:
../raylib-cpp/include/./Functions.hpp: At global scope:
../raylib-cpp/include/./Functions.hpp:170:35: warning: ‘std::vector<std::__cxx11::basic_string<char> > raylib::LoadDroppedFiles()’ defined but not used [-Wunused-function]
  170 | RLCPPAPI std::vector<std::string> LoadDroppedFiles() {
      |                                   ^~~~~~~~~~~~~~~~
../raylib-cpp/include/./Functions.hpp:153:35: warning: ‘std::vector<std::__cxx11::basic_string<char> > raylib::LoadDirectoryFiles(const std::string&)’ defined but not used [-Wunused-function]
  153 | RLCPPAPI std::vector<std::string> LoadDirectoryFiles(const std::string& dirPath) {
      |                                   ^~~~~~~~~~~~~~~~~~
../raylib-cpp/include/./Functions.hpp:73:22: warning: ‘std::string raylib::LoadFileText(const std::string&)’ defined but not used  -Wunused-function]
   73 | RLCPPAPI std::string LoadFileText(const std::string& fileName) {
      |                      ^~~~~~~~~~~~
ninja: build stopped: subcommand failed.```

**Comment by RobLoach** [comment]
What version of raylib are you linking against in bitsim?

**Comment by AbhayAysola** [comment]
4.2, the latest one I think

**Comment by RobLoach** [comment]
I believe DrawCubeTexture() was removed/renamed in the `master` version of raylib, but it exists in 4.2. You might be on `master`.

**Comment by AbhayAysola** [comment]
yep that's right, thanks for the help. I had a feeling it was something stupid from my end

One last thing though, the errors are all gone but I'm getting a few unused functions - `LoadDroppedFiles`, `LoadDirectoryFiles`, and `LoadFileText`. Any clue what that's about?

**Comment by RobLoach** [comment]
Made an issue for that https://github.com/RobLoach/raylib-cpp/issues/228 .... Should likely clarify the raylib version too, so I'll make an issue for that.

**Comment by AbhayAysola** [comment]
yep that makes sense

**Comment by RobLoach** [comment]
Would love your help testing the VERSION check once that's up though! Thanks so much for pushing this forwards.
