### ISSUE TITLE
Raylib has moved and removed 5 functions

### ISSUE THREAD

**Issue by pkeir** [RobLoach/raylib-cpp#232]
In November Raylib either moved (to examples) or removed `::DrawCubeTexture()`, `::DrawCubeTextureRec()`, `::DrawTextureTiled()`, `::DrawTextureQuad()` and `::DrawTexturePoly()` from raylib.h. (See [here](https://github.com/raysan5/raylib/commits/master/src/raylib.h).)

In raylib-cpp these functions are used in `TextureUnmanaged.hpp` and `Vector3.hpp`.

**Comment by RobLoach** [comment]
While raylib-cpp targets 4.2 currently, I think it's okay if we remove those functions entirely. Mind sending a Pull Request?

**Comment by pkeir** [comment]
No problem. That's it now.

**Comment by RobLoach** [comment]
Thanks so much :+1:
