### ISSUE TITLE
Where `SetConfigFlags`?

### ISSUE THREAD

**Issue by traversebitree** [RobLoach/raylib-cpp#234]
Where `SetConfigFlags`?  For example, `SetConfigFlags(FLAG_MSAA_4X_HINT);`

**Comment by RobLoach** [comment]
Not implemented. Not sure it's required, but happy to have it added.

**Comment by Sticky-fingerz** [comment]
I have the same problem.
Raylib needs to enable MSAA calling SetConfigFlags(FLAG_MSAA_4X_HINT) before InitWindow().
But raylib-cpp has no SetConfigFlags,so next program is working only resize flag only.
```
raylib::Window window(1280, 720 "title");
window.SetState(FLAG_WINDOW_RESIZABLE | FLAG_MSAA_4X_HINT);
```
Is there another way?
