### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DoubleShotgun** [RobLoach/raylib-cpp#237]
All I did is run `g++ main.cpp -lraylib -lGL -lm -lpthread -ldl -lrt -lX11`

This error appeared

`In file included from /usr/local/include/Color.hpp:7,
                 from /usr/local/include/raylib-cpp.hpp:39,
                 from main.cpp:1:
/usr/local/include/Vector4.hpp: In member function ‘std::pair<raylib::Vector3, float> raylib::Vector4::ToAxisAngle()’:
/usr/local/include/Vector4.hpp:105:45: note: parameter passing for argument of type ‘std::pair<raylib::Vector3, float>’ when C++17 is enabled changed to match C++14 in GCC 10.1
  105 |     std::pair<Vector3, float> ToAxisAngle() {
      |                                             ^
In file included from /usr/local/include/TextureUnmanaged.hpp:11,
                 from /usr/local/include/Font.hpp:9,
                 from /usr/local/include/raylib-cpp.hpp:40:
/usr/local/include/Image.hpp: In static member function ‘static Image raylib::Image::GradientV(int, int, Color, Color)’:
/usr/local/include/Image.hpp:137:18: error: ‘::GenImageGradientV’ has not been declared; did you mean ‘GenImageGradientSquare’?
  137 |         return ::GenImageGradientV(width, height, top, bottom);
      |                  ^~~~~~~~~~~~~~~~~
      |                  GenImageGradientSquare
/usr/local/include/Image.hpp: In static member function ‘static Image raylib::Image::GradientH(int, int, Color, Color)’:
/usr/local/include/Image.hpp:144:18: error: ‘::GenImageGradientH’ has not been declared; did you mean ‘GenImageGradientSquare’?
  144 |         return ::GenImageGradientH(width, height, left, right);
      |                  ^~~~~~~~~~~~~~~~~
      |                  GenImageGradientSquare
[Finished in 3.2s with exit code 1]
[shell_cmd: g++ main.cpp -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o /home/user/out && ~/out && rm ~/out]
[dir: /sdcard/Raylib]
[path: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/data/data/com.termux/files/usr/bin:/system/bin:/system/xbin]`

**Comment by RobLoach** [comment]
Is this on raylib 4.5 or raylib 4.7?  Try the `next` branch perhaps?

**Comment by DoubleShotgun** [comment]
4.5

**Comment by DoubleShotgun** [comment]
Also I'm a noob with github, how would i install this?

**Comment by RobLoach** [comment]
You are using raylib's `master` branch right now, which compiles against raylib-cpp's `next` branch. Check out the `next` branch of `raylib-cpp`, or download it here https://github.com/RobLoach/raylib-cpp/tree/next

**Comment by DoubleShotgun** [comment]
Now I'm getting this

`In file included from /sdcard/Raylib/include/./Color.hpp:7,
                 from /sdcard/Raylib/include/raylib-cpp.hpp:39,
                 from /sdcard/Raylib/main.cpp:1:
/sdcard/Raylib/include/././Vector4.hpp: In member function ‘std::pair<raylib::Vector3, float> raylib::Vector4::ToAxisAngle()’:
/sdcard/Raylib/include/././Vector4.hpp:105:45: note: parameter passing for argument of type ‘std::pair<raylib::Vector3, float>’ when C++17 is enabled changed to match C++14 in GCC 10.1
  105 |     std::pair<Vector3, float> ToAxisAngle() {
      |                                             ^
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `raylib::LoadFileText(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text+0x18): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/usr/bin/ld: main.cpp:(.text+0x28): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: main.cpp:(.text+0x44): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text+0x5c): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text+0x70): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `raylib::LoadDirectoryFiles(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text+0xa8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `main':
main.cpp:(.text+0x248): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: main.cpp:(.text+0x288): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text+0x290): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text+0x298): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: main.cpp:(.text+0x2c8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text+0x2d0): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text+0x424): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text+0x434): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text+0x448): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text+0x458): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `raylib::RaylibException::RaylibException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text._ZN6raylib15RaylibExceptionC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6raylib15RaylibExceptionC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x18): undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `raylib::TextureUnmanaged::Load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text._ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x18): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/usr/bin/ld: main.cpp:(.text._ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x60): undefined reference to `__cxa_allocate_exception'
/usr/bin/ld: main.cpp:(.text._ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x94): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text._ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xac): undefined reference to `__cxa_throw'
/usr/bin/ld: main.cpp:(.text._ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN6raylib16TextureUnmanaged4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xb8): undefined reference to `__cxa_free_exception'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `raylib::Window::Init(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)':
main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0x38): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
/usr/bin/ld: main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0x68): undefined reference to `__cxa_allocate_exception'
/usr/bin/ld: main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0x74): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0xa8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0xb0): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0xc8): undefined reference to `__cxa_throw'
/usr/bin/ld: main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0xd4): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text._ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj[_ZN6raylib6Window4InitEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj]+0xdc): undefined reference to `__cxa_free_exception'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::~_Alloc_hider()':
main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_Alloc_hiderD2Ev[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_Alloc_hiderD5Ev]+0x10): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string<std::allocator<char> >(char const*, std::allocator<char> const&)':
main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC5IS3_EEPKcRKS3_]+0x20): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data()'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC5IS3_EEPKcRKS3_]+0x30): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&)'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC5IS3_EEPKcRKS3_]+0x48): undefined reference to `std::__throw_logic_error(char const*)'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x30): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::get_allocator() const'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x50): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::allocator<char> const&)'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x58): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x60): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x68): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x80): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x90): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*, unsigned long)'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0x9c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0xac): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_[_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8_]+0xc0): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)::_Guard::~_Guard()':
main.cpp:(.text._ZZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tagEN6_GuardD2Ev[_ZZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tagEN6_GuardD5Ev]+0x24): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)':
main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag]+0x44): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag]+0x50): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data(char*)'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag]+0x60): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_capacity(unsigned long)'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag]+0x74): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data()'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag]+0x8c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag]+0x98): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char const*, char const*)'
/usr/bin/ld: main.cpp:(.text._ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPKcEEvT_S8_St20forward_iterator_tag]+0xac): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_set_length(unsigned long)'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::allocator_traits<std::allocator<char> >::select_on_container_copy_construction(std::allocator<char> const&)':
main.cpp:(.text._ZNSt16allocator_traitsISaIcEE37select_on_container_copy_constructionERKS0_[_ZNSt16allocator_traitsISaIcEE37select_on_container_copy_constructionERKS0_]+0x1c): undefined reference to `std::allocator<char>::allocator(std::allocator<char> const&)'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_S_check_init_len(unsigned long, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)':
main.cpp:(.text._ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_S_check_init_lenEmRKS6_[_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_S_check_init_lenEmRKS6_]+0x54): undefined reference to `std::__throw_length_error(char const*)'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::__new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::deallocate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned long)':
main.cpp:(.text._ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10deallocateEPS5_m[_ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10deallocateEPS5_m]+0x24): undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::__new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocate(unsigned long, void const*)':
main.cpp:(.text._ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8allocateEmPKv[_ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8allocateEmPKv]+0x58): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: main.cpp:(.text._ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8allocateEmPKv[_ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8allocateEmPKv]+0x5c): undefined reference to `std::__throw_bad_alloc()'
/usr/bin/ld: main.cpp:(.text._ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8allocateEmPKv[_ZNSt15__new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8allocateEmPKv]+0x68): undefined reference to `operator new(unsigned long)'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `void std::_Destroy<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
main.cpp:(.text._ZSt8_DestroyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEvPT_[_ZSt8_DestroyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEvPT_]+0x10): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >* std::__do_uninit_copy<char**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*>(char**, char**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
main.cpp:(.text._ZSt16__do_uninit_copyIPPcPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEET0_T_SA_S9_[_ZSt16__do_uninit_copyIPPcPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEET0_T_SA_S9_]+0x64): undefined reference to `__cxa_begin_catch'
/usr/bin/ld: main.cpp:(.text._ZSt16__do_uninit_copyIPPcPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEET0_T_SA_S9_[_ZSt16__do_uninit_copyIPPcPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEET0_T_SA_S9_]+0x74): undefined reference to `__cxa_rethrow'
/usr/bin/ld: main.cpp:(.text._ZSt16__do_uninit_copyIPPcPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEET0_T_SA_S9_[_ZSt16__do_uninit_copyIPPcPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEET0_T_SA_S9_]+0x7c): undefined reference to `__cxa_end_catch'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `void std::_Construct<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char*&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char*&)':
main.cpp:(.text._ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJRPcEEvPT_DpOT0_[_ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJRPcEEvPT_DpOT0_]+0x40): undefined reference to `std::allocator<char>::allocator()'
/usr/bin/ld: main.cpp:(.text._ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJRPcEEvPT_DpOT0_[_ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJRPcEEvPT_DpOT0_]+0x5c): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: main.cpp:(.text._ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJRPcEEvPT_DpOT0_[_ZSt10_ConstructINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEJRPcEEvPT_DpOT0_]+0x6c): undefined reference to `std::allocator<char>::~allocator()'
/usr/bin/ld: /tmp/cc5S3ZSq.o:(.data.rel.ro._ZTVN6raylib15RaylibExceptionE[_ZTVN6raylib15RaylibExceptionE]+0x20): undefined reference to `std::runtime_error::what() const'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `raylib::RaylibException::~RaylibException()':
main.cpp:(.text._ZN6raylib15RaylibExceptionD2Ev[_ZN6raylib15RaylibExceptionD5Ev]+0x20): undefined reference to `std::runtime_error::~runtime_error()'
/usr/bin/ld: /tmp/cc5S3ZSq.o: in function `raylib::RaylibException::~RaylibException()':
main.cpp:(.text._ZN6raylib15RaylibExceptionD0Ev[_ZN6raylib15RaylibExceptionD5Ev]+0x1c): undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: /tmp/cc5S3ZSq.o:(.data.rel.ro._ZTIN6raylib15RaylibExceptionE[_ZTIN6raylib15RaylibExceptionE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/bin/ld: /tmp/cc5S3ZSq.o:(.data.rel.ro._ZTIN6raylib15RaylibExceptionE[_ZTIN6raylib15RaylibExceptionE]+0x10): undefined reference to `typeinfo for std::runtime_error'
/usr/bin/ld: /tmp/cc5S3ZSq.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'`

**Comment by DoubleShotgun** [comment]
Never mind, I realise I was compiling with `cc` instead of `g++`, that error was my fault

**Comment by RobLoach** [comment]
Glad you got it working!
