### ISSUE TITLE
Compile errors: no member named 'GenImageGradientV' in the global namespace

### ISSUE THREAD

**Issue by ahmed00101** [RobLoach/raylib-cpp#242]
include/CPP/./Image.hpp:137:18: error: no member named 'GenImageGradientV' in the global namespace
        return ::GenImageGradientV(width, height, top, bottom);
               ~~^
include/CPP/./Image.hpp:144:18: error: no member named 'GenImageGradientH' in the global namespace
        return ::GenImageGradientH(width, height, left, right);

Compiler command:
		g++ -std=c++17 -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL libD/libraylib.a src/game.cpp -o game -Iinclude/CPP -Iinclude

**Comment by RobLoach** [comment]
Use raylib 4.5... Or switch to the `next` branch of raylib-cpp.
