### ISSUE TITLE
Vector operators `+`, `==` and `-` are not `const`

### ISSUE THREAD

**Issue by GregTheMadMonk** [RobLoach/raylib-cpp#246]
`next` branch, problem is essentially the title.
Given
```cpp
const Vector3 a{ ... };
const Vector3 b{ ... };
```
one essentially can't do
```cpp
const auto c = a + b;
```

**Comment by RobLoach** [comment]
Those would be great to have 👍... Are you able to add them?

**Comment by Vanny-Chuck** [comment]
@GregTheMadMonk Can you close this? It helps people find the real problems.
