### ISSUE TITLE
how to upgrade to raylib5.0

### ISSUE THREAD

**Issue by HotHat** [RobLoach/raylib-cpp#264]
#error "raylib-cpp requires at least raylib 4.5.0"

Error C2039	"DrawLineBezierQuad":  not "`global namespace'" member   raylib-cpp\include\Vector2.hpp	365	

Error C2660	“DrawLineBezierQuad”:   not  "`global namespace'" member  raylib-cpp\include\Vector2.hpp	365	

Error C2039	"GenImageGradientV":  not  "`global namespace'" member  raylib-cpp\include\Image.hpp	137	

Error C3861	“GenImageGradientH”: can't find identity  raylib-cpp\include\Image.hpp	144

**Comment by RobLoach** [comment]
5.0 isn't out yet. But a lot of what's included in it is in the next branch

**Comment by RobLoach** [comment]
It's out
