### ISSUE TITLE
Error Cmake 

### ISSUE THREAD

**Issue by drafold** [RobLoach/raylib-cpp#269]
So Im Try to Build the raylib-cpp with using cmake so im dont know how to  fix the same error my device is a ubuntu linux 20.04 

```bash
root@localhost:~/patsher/modules/raygui-cpp/build# cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.17 or higher is required.  You are running version 3.16.3


-- Configuring incomplete, errors occurred!
root@localhost:~/patsher/modules/raygui-cpp/build# make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by RobLoach** [comment]
sounds like you'll need to upgrade cmake to >=3.17

**Comment by RobLoach** [comment]
Alternatively, if you could try changing the min requiremeent in the cmake file to 3.16.3 and it works, I'd be happy to help make those changes upstream
