### ISSUE TITLE
Vector2Rotate(Vector2 v, float angle) takes a radian, not a degree

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [RobLoach/raylib-cpp#271]
![image](https://github.com/RobLoach/raylib-cpp/assets/111327195/2c91f11f-7a7a-4c93-a50c-09eb539d27d3)
![image](https://github.com/RobLoach/raylib-cpp/assets/111327195/613a2214-8044-4393-8531-d6a927a474e2)
`cosf(float angle)` and `sinf(float angle)` both takes a radian as parameter, not degrees.

**Comment by RobLoach** [comment]
Good catch, thanks. Would you mind sending a pull request for it?

**Comment by Ataraxia-Mechanica** [comment]
Oops, this is already fixed in merge request #268, I was using version 5.0.0 and it was before the fix.

**Comment by RobLoach** [comment]
Sweet! I'll go through another round of tests and make a release
