### ISSUE TITLE
Add Keyboard class for handling raylib keyboard related functions

### ISSUE THREAD

**Issue by swiderskis** [RobLoach/raylib-cpp#274]
I noticed there are classes defined for handling mouse (Mouse.hpp) and gamepad (Gamepad.hpp) inputs. However, there are also keyboard input functions in raylib that are not defined in raylib-cpp.
![image](https://github.com/RobLoach/raylib-cpp/assets/66870324/07c9cde3-709d-47a2-a1d9-379d5a7e485c)
I think it would make sense to define these in a Keyboard class. If you agree, would you like me to make a PR for this?

**Comment by swiderskis** [comment]
Also, perhaps the SetExitKey() function should be added as a method of the Window class?

**Comment by RobLoach** [comment]
yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaas

**Comment by swiderskis** [comment]
Added in #275
