### ISSUE TITLE
Local build error for AutomationEventList

### ISSUE THREAD

**Issue by kyomawolf** [RobLoach/raylib-cpp#279]
I've had an issue with building the current master/5.0.1 version.
```
    AutomationEventList& Unload() {
        ::UnloadAutomationEventList(this);
        return *this;
    }

```
This bit caused a compiler error as the function prototype of the raylib 5.1 is this:
`RLAPI void UnloadAutomationEventList(AutomationEventList list);`
So I changed the `this` to `*this`, fixing it locally for me, but that causes the build pipeline to fail, so I'm confused who is right. Is the build pipeline broken, or is it just my system?
This is my build setup:
Kubuntu 22.04
Raylib 5.1
C compiler version GNU 11.4.0

**Comment by RobLoach** [comment]
Actually, would you changing it to a void, without a return??? I don't think you should really need to use it at all after it's unloaded.

**Comment by kyomawolf** [comment]
I mean the problem still remains, as the return value does not affect the input parameter of the underlying raylib function

**Comment by kyomawolf** [comment]
Thought I was using raylib 5.0; though I am using 5.1-dev. The signature changes from `UnloadAutomationEventList *list` to `UnloadAutomationEventList list`

**Comment by RobLoach** [comment]
Hmm, perhaps we add a `#if` check for the version and flip as needed :thinking:

**Comment by kyomawolf** [comment]
It is not a released version. I basically used the raylib master branch. I dont think its useful, just update it with v5.1 support
