### ISSUE TITLE
update const std::string& to const char*

### ISSUE THREAD

**Issue by mips64-el** [RobLoach/raylib-cpp#292]
This library overuses std::string type, making a temporary copy every time you pass a const char* into a const std::string& argument making unnecessary copies. It should support mainly const char*, or support both with an intermediate struct.

**Comment by kyomawolf** [comment]
why would you be using `char*` anyway?

**Comment by mips64-el** [comment]
i would use const char* mainly because there's no need of overusing the creation of std::string each time you call raylib::Texture2D texture("space.png") for example, it will copy your const char* into a temporary std::string. Raylib sadly only accepts const char* and it would be really nice if raylib would accept std::string_view but raylib it's not a c++ library.

**Comment by kyomawolf** [comment]
I kind of see the point, but if I work with normal strings, this makes it weird and misses the point of having a c++ wrapper. I rather suggest doing it the proper c++17 way and using string_view instead

**Comment by kyomawolf** [comment]
That is a good point, then I would suggest this:
```class s_string {
private:
const char* internal;
public:
s_string(const char *s) : internal(s) { }
s_string(std::string& s) : internal(s.c_str()) {}
}

**Comment by mips64-el** [comment]
yea, acceptable 
class s_string {
    const char* m_ptr;
public:
     s_string(const char *s) : m_ptr(s) { }
     s_string(const std::string& s) : m_ptr(s.c_str()) {}
     operator const char*() { return m_ptr; }
};
We should ask @RobLoach

**Comment by RobLoach** [comment]
Making our own class wrapper seems excessive when both string and string_view already exist?

**Comment by mips64-el** [comment]
@RobLoach you can't use string_view for raylib, because you can't specify to raylib the size of the actual string, because it's not even null terminated, and string would be a waste of performance copying const char* contents every time you need to call any function with const std::string&.

**Comment by RobLoach** [comment]
Thanks for the clarification. After some thought on this, I think it may be better to overload the methods. Then if you pass in a `const char*`, it just calls DrawText directly without any new object at all or casting or anything.

``` c
void DrawText(const char* text, int posX = 0, int posY = 0, int fontSize = 10.0f) const {
    ::DrawText(text, posX, posY, fontSize, *this);
}

void DrawText(const std::string& text, int posX = 0, int posY = 0, int fontSize = 10.0f) const {
    ::DrawText(text.c_str(), posX, posY, fontSize, *this);
}
```

**Comment by RobLoach** [comment]
Added a few of the overloads, but let me know if there are any others that you think would benefit from it.
