### ISSUE TITLE
Window closing immediately if called from a class.

### ISSUE THREAD

**Issue by Boyfinn** [RobLoach/raylib-cpp#313]
Here is what I have:
main.h:
```
#ifndef MAIN_H
#define MAIN_H
#include "game.h"
Game _game;
#endif
```

main.cpp:
```
#include "main.h"

//ASSETS_PATH macro leading everything in assets folder

int main() {
    _game.Initialize();
    _game.Run();
}
```
game.h:
```
#ifndef GAME_H
#define GAME_H

#include "raylib.h"
#include "raylib-cpp.hpp"
#include <string>

struct G_WINDOW
{
    std::string WINDOW_TITLE;
    int WINDOW_WIDTH;
    int WINDOW_HEIGHT;
};

class Game
{
    protected:
    G_WINDOW _windowProperties =
    {
        .WINDOW_TITLE = "GAME",
        .WINDOW_WIDTH = 1920,
        .WINDOW_HEIGHT = 1080
    };
    raylib::Window _gameWindow;

    private:
    void Start();
    void Update();

    public:
    void Initialize();
    void Run();
    void Draw();
};
#endif
```
game.cpp:
```
#include "game.h"
void Game::Initialize()
{
    raylib::Window _gameWindow(_windowProperties.WINDOW_WIDTH, _windowProperties.WINDOW_HEIGHT, _windowProperties.WINDOW_TITLE);
    _gameWindow.SetExitKey(KEY_ESCAPE);
    SetTargetFPS(60);
}
void Game::Run()
{
    while (!_gameWindow.ShouldClose())
    {
        Draw();
    }
}

void Game::Draw()
{
    BeginDrawing();

    _gameWindow.ClearBackground(RAYWHITE);

    DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);

    EndDrawing();
}
```
**Issue:**
Game window closes immediately without any errors on console/gcc debug output. A comparable example has worked before on vanilla raylib. No difference whether I use while(!_gameWindow.ShouldClose()) or just a while(true) loop

**Comment by Boyfinn** [comment]
Calling the raylib::window constructor in this manner doesn't initialize GLFW properly, thus the ShouldClose() considiton is never met. This can be sort of worked around by:

1. Declaring a raylib::Window without calling it's constructor,
2. Calling said raylib::Window object's .Init() member as if you were calling the window's constructor.

**Comment by RobLoach** [comment]
If your initialize() Game function, you're creating a new Window variable that has the scope only within the Initialize() function. Once the window is made, it will close it since C++ will destruct the object.

``` cpp
void Game::Initialize()
{
    raylib::Window _gameWindow(_windowProperties.WINDOW_WIDTH, _windowProperties.WINDOW_HEIGHT, _windowProperties.WINDOW_TITLE);
    _gameWindow.SetExitKey(KEY_ESCAPE);
    SetTargetFPS(60);
}
```

Instead, you might want to do soemthing like...

```
#include "main.h"

//ASSETS_PATH macro leading everything in assets folder

int main() {
  Game game;
  game.Initialize();
  game.Run();
}
```

``` cpp
void Game::Initialize()
{
    _gameWindow.SetSize(_windowProperties.WINDOW_WIDTH, _windowProperties.WINDOW_HEIGHT);
    _gameWindow.SetTitle(_windowProperties.WINDOW_TITLE);
    _gameWindow.SetExitKey(KEY_ESCAPE);
    SetTargetFPS(60);
}
```

**Comment by Boyfinn** [comment]
Isn't the scope object wide? Since in game.h I've defined _gameWindow under protected members?

**Comment by RobLoach** [comment]
If defining a new variable with the same name in a sub-scope, it will be a new variable... For example...

``` c
int boyfinn = 5;
for (int rob = 0; rob < 5; rob++) {
    int boyfinn = 10;
}
printf("Boyfinn: %d\n", boyfinn);

for (int i = 0; i < 5; i++) {
    boyfinn = 10;
}
printf("Boyfinn: %d\n", boyfinn);
```

The above will output....
```
Boyfinn: 5
Boyfinn: 10
```

**Comment by kyomawolf** [comment]
you are shadowing the variable previously defined in the class itself, why the compiler doesn't complain is actually a compiler bug/feature.
I would suggest a couple of changes so that you don't have that issue:
- Don't create globals if they are not absolutely necessary / required by the framework (or you are doing embedded, then do whatever)
- you have to initialize class members in their constructor, so doing that in a separate function wont do, the compilation will fail
- either you create a function variable as robloach suggested, or you [use the singleton pattern to achieve a similar effect](https://refactoring.guru/design-patterns/singleton)

**Comment by RobLoach** [comment]
@Boyfinn Did you get it working?

**Comment by Boyfinn** [comment]
@RobLoach Yeah, I got it working (Sorry for the late reply). I was calling some raylib::Window members in the wrong order.

**Comment by RobLoach** [comment]
Great to hear
