### ISSUE TITLE
How to install for visual studio w/ or w/o vcpkg and is there support for networking/win32?

### ISSUE THREAD

**Issue by td-at-coding** [RobLoach/raylib-cpp#314]
Hello, I am trying to install this repository properly for visual studio and I am wondering if there's a way to add networking, tcp websockets and what not.  For some reason the C repository has problems with win32 that's why I am trying to install this version of raylib. Thank you.

**Comment by kyomawolf** [comment]
A Webtechstack is kind of out of scope for this project? You would need to add it yourself. If you have issues with taylib on windows, you should maybe create an issue there

**Comment by td-at-coding** [comment]
Sorry, I was just wondering if there’s naming conflicts with windows.h at all.

**Comment by kyomawolf** [comment]
there should be no namimg conflict afaik.
here is a setupguide for raylib on windows:
https://github.com/raysan5/raylib/wiki/Working-on-Windows
For raylib-cpp it is a header only library, having it in any include path should make it work

**Comment by td-at-coding** [comment]
Oh I see… I thought this was a standalone project. Sorry about the confusion.
