### ISSUE TITLE
`string_view` instead of `string`?

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/raylib-cpp#318]

**Comment by furudbat** [comment]
One problem with `std::string_view` is, it's not guaranteed to be a null-terminated string.

I would love to replace `const std::string&` with something like `std::string_view`, but I wouldn't recommend it.

We probably need something like [zstring_view](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rstr-zstring). Shouldn't be that hard to [implement](https://github.com/Aszarsha/zstring_view/blob/master/zstring_view.hpp)

**Comment by RobLoach** [comment]
Agreed, and because performance isn't the primary goal of this library, it may not be worth its adoption.
