### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/raylib-cpp#331]
Add a clang-format definition file, and apply its coding standards.

**Comment by furudbat** [comment]
I was literally in the process of adding an [`.clang-format`](https://github.com/furudbat/raylib-cpp20/blob/main/.clang-format) for my own fork.

* try to keep the [current](https://github.com/RobLoach/raylib-cpp/blob/master/CPPLINT.cfg) format
* respecting [raylib](https://github.com/raysan5/raylib/blob/master/CONVENTIONS.md) (Name Conventions, etc.)

It needs a bit more fine tuning, 
but having an format file and living with it's decision is better then having no file and chaos.

_(I personally don't care about formatting, I just run the formatter and learn to read the code)_

**Comment by furudbat** [comment]
I would also recommend adding an [.clang-tidy](https://github.com/furudbat/raylib-cpp20/blob/main/.clang-tidy) and [.cmake-format.yaml](https://github.com/furudbat/raylib-cpp20/blob/main/.cmake-format.yaml) file.

**Comment by RobLoach** [comment]
Sounds good with me. Thanks a lot.

**Comment by RobLoach** [comment]
Here's one that I used on another project. Not sure how well it appllies here tho https://github.com/RobLoach/nuklear_console/blob/master/.clang-format
