### ISSUE TITLE
Sample project does not compile

### ISSUE THREAD

**Issue by quentin-dev** [RobLoach/raylib-cpp#48]
I'm currently trying to compile the default project using your instructions, but keep getting errors like
```
/[...]/raylib-cpp/projects/CMake/build/_deps/raylib-cpp-src/include/./Image.hpp:113:10: error: ‘::LoadImageAnim’ has not been declared; did you mean ‘LoadImageRaw’?
  113 |    set(::LoadImageAnim(fileName.c_str(), frames));
      |          ^~~~~~~~~~~~~
      |          LoadImageRaw
```

Do you have any idea what I can do to fix it ?

**Comment by RobLoach** [comment]
Ah, it's because we've brought in the most recent changes from raylib. I might revert and re-tag.

**Comment by RobLoach** [comment]
Does this fix it? https://github.com/RobLoach/raylib-cpp/pull/49

**Comment by quentin-dev** [comment]
Yes, the project compiles correctly on that branch, although there are still some warnings like this one:
```
/[...]/raylib-cpp/projects/CMake/build/_deps/raylib-cpp-src/include/./Color.hpp:206:2: warning: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’
  206 |  inline Color Color::LightGray = ::LIGHTGRAY;
```
Thanks for looking into it so fast !

**Comment by RobLoach** [comment]
Just removed the inline Color variables entirely. Caused more harm than good. Thanks a lot, @quentin-dev!
