### ISSUE TITLE
no member named 'IsAudioBufferProcessed' in the global namespace

### ISSUE THREAD

**Issue by IsaacBreen** [RobLoach/raylib-cpp#5]
Reporting in case somebody else runs into the same problem when importing raylib.hpp.

```error: no member named 'IsAudioBufferProcessed' in the global namespace; did you mean 'IsAudioStreamProcessed'?```

This seems to be because`IsAudioBufferProcessed` was [renamed](https://github.com/raysan5/raylib/blob/master/examples/audio/audio_raw_stream.c) to`IsAudioStreamProcessed` in August 2019. I guess the CPP bindings simply haven't been updated since then.

**Comment by RobLoach** [comment]
Thanks! The Cpp bindings likely need an update. They are still young so could do with lots of ideas on how they could improve too

**Comment by RobLoach** [comment]
Would you mind sending up a Pull Request with the change? Would really appreciate the help.

**Comment by RobLoach** [comment]
This should be fixed now! Thanks a lot.
