### ISSUE TITLE
Inline variables in Color.hpp

### ISSUE THREAD

**Issue by fivefortyam** [RobLoach/raylib-cpp#51]
lines 206 - 231 won't compile because they are declared as inline variables.
[Error] 'raylib::Color::DarkBlue' declared as an 'inline' variable
[Error] 'raylib::Color::Purple' declared as an 'inline' variable
etc.

**Comment by RobLoach** [comment]
You're right. I'm unsure of a good way around this.

As static, they're added twice if you include the header twice. Need a RAYLIB_CPP_IMPLEMENTATION define, but that's a pretty sad design. Do you have any ideas?

**Comment by fivefortyam** [comment]
I am using Dev-C++ built on April 27, 2015. So probably C++11. and I am not sure about exactly what the problem is as I have little experience with c++.

**Comment by llsanketll** [comment]
Add this line of code to set your c++ version `set(CMAKE_CXX_STANDARD 17)` in your CMakeList.txt right below the line `# https://cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html` worked for me and if the window didn't open after that try changing the opengl version by `set(GRAPHICS GRAPHICS_API_OPENGL_21)`
