### ISSUE TITLE
Unable to make my raylib-cpp project into an apk

### ISSUE THREAD

**Issue by ghostly-developer** [RobLoach/raylib-cpp#55]
I've been trying to use the makefile to make my raylib-cpp projects into apk. I am currently stuck on trying to find out how fix this linker error. Does anyone have any solutions?

(Error Message Attached)
![Capture](https://user-images.githubusercontent.com/70617805/92690121-9465bd80-f36a-11ea-8ea8-94fbd8a9bcf5.JPG)

**Comment by RobLoach** [comment]
Hmmm, looks like it's not finding raylib. You might have to link it?

**Comment by RobLoach** [comment]
In addition, it should be `if(IsAudioDeviceReady()) {`
