### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by QuantScientist** [RobLoach/raylib-cpp#56]
First,
Thank you so much for this CMake project! 

I had to set these otherwise the projects did not compile:
```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

Now:
```
core_3d_camera_first_person.cpp
F:\Dropbox\Tech\production\ppc\raylib-cpp\examples\core\core_3d_camera_first_person.cpp(42): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data

```

And:
```
physics_demo.cpp
F:\Dropbox\Tech\production\ppc\raylib-cpp\vendor\raylib\src\physac.h(410): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
```

And some more ...

**Comment by RobLoach** [comment]
Thanks for the reports.

Been consdering removing the Colors, as it causes issues across different versions of C++.

**Comment by RobLoach** [comment]
Mind getting a fresh pull and seeing if you still get the error? Seems to be working for me.

**Comment by RobLoach** [comment]
The CXX standard is now set. Looking like it's passing again. Thanks!
