### ISSUE TITLE
How to install raylib-cpp to standard paths like /usr/local/lib etc.

### ISSUE THREAD

**Issue by ianpan870102** [RobLoach/raylib-cpp#58]
I am currently using your suggested approach `#include "path/to/raylib-cpp.hpp"`, and it works fine so far. However, I'd love to install raylib-cpp to standard directories, `usr/local/lib` and `/usr/local/include` like the way I did it with raylib (reference: https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux)

Is there a recommended way of doing so? I'm rather new to working with C/C++ and makefiles etc. but would love to learn more.

Btw, thanks for the effort, this OOP wrapper is very clean IMO and makes code looks so sleek!

**Comment by RobLoach** [comment]
It uses `#include "raylib.h"`, so as long as usr/local/lib is in the PATH, then it should detect it okay. I'm unsure how raylib in packages works, however. I've tended to include it manually myself...

You likely know more than me!

**Comment by ianpan870102** [comment]
I see, thanks for the reply!
