### ISSUE TITLE
Undeclared identifier "depthTexture"

### ISSUE THREAD

**Issue by ianpan870102** [RobLoach/raylib-cpp#59]
In `include/RenderTexture2D.hpp` there are multiple references towards `depthTexture`. However, the RenderTexture2D struct has no such member. For your reference, this is the definition of raylib's RenderTexture2D struct:

```c
// RenderTexture2D type, for texture rendering
typedef struct RenderTexture2D {
    unsigned int id;        // OpenGL Framebuffer Object (FBO) id
    Texture texture;      // Color buffer attachment texture
    Texture depth;        // Depth buffer attachment texture
} RenderTexture2D;

// RenderTexture type, same as RenderTexture2D
typedef RenderTexture2D RenderTexture;
```

Is it an inconsistency across different versions of raylib?

**Comment by RobLoach** [comment]
Likely a change in a recent raylib.... Are you on the latest `master` of raylib.h?

**Comment by RobLoach** [comment]
found it https://github.com/raysan5/raylib/commit/fa2c1146366557e5ce779d8b5c2575579dfa6389#diff-0a6362cf3403cf2e074dda26d1f2776f

**Comment by ianpan870102** [comment]
Yes I'm on the latest master of raylib.h. Thanks for the fix!
