### ISSUE TITLE
Make Errors on raylib-cpp

### ISSUE THREAD

**Issue by CodingCor** [RobLoach/raylib-cpp#69]
I just tried to clone the raylib-cpp repo and build it the way you described it in your readme.md. 
However i get a bunch of errors in the make process. 

I would really appreciate your help as your library seems quite promising. 
Below are the errors thrown by the make process:

https://pastebin.pl/view/427e0018

**Comment by RobLoach** [comment]
It's using this version from raylib...
https://github.com/raysan5/raylib/tree/032b2db3983836474bef3ee45e90967617146e49

**Comment by CodingCor** [comment]
I don't quite get it is there a supported C++ API right now or not?

**Comment by CodingCor** [comment]
Well i downloaded raylib through the official Arch Repository, being at version 3.0.0-1 as well as the raylib-cpp version from github, so i really doubt this is the problem.

**Comment by Vyber90** [comment]
Same issue here, from the last release.

**Comment by Vyber90** [comment]
@CodingCor And, by the way, I just made it work by downloading the last commit, not release, from both raylib and raylib-cpp and linking all the files correctly. Perhaps this is not the most stable way of doing this, but it works and can be useful until we get new releases.

**Comment by RobLoach** [comment]
Once the next release of raylib is out, I'll cut a new tag so that the releases are synced. I understand the latest releases aren't aligned right now.

**Comment by ianpan870102** [comment]
@RobLoach Thanks for the brilliant work, Rob!

**Comment by CodingCor** [comment]
Thanks a lot. I will look into this myself as soon as i got time. I consider this matter closed now.
