### ISSUE TITLE
Need guide for newbie

### ISSUE THREAD

**Issue by sbgssol** [RobLoach/raylib-cpp#7]
Hello,

I'm absolutely new here.
I want to build my game with Visual Studio and raylib for cpp.
I glance at the library for C language and I found that it has a raylib.dll, raylib.lib and a header file (in the windows installer release) and I think it's enough to build and run the game.
So, what should I do with this to build my game with C++ language?
Thanks!

**Comment by RobLoach** [comment]
raylib-cpp doesn't provide binaries currently, but if you link raylib in your project successfully, then you can just include raylib.hpp and it should work okay.

Something like this:
https://github.com/raysan5/raylib/tree/master/projects/VS2017

If you get something working, I'm curious. Been looking to grow the projects directory for some examples of using it in different IDEs.

**Comment by RobLoach** [comment]
It's also worth noting that you don't need `raylib-cpp` to use raylib in C++. You can include the C library directly in a C++ application without issue. raylib-cpp just adds some helpful object wrappers.

**Comment by sbgssol** [comment]
Oh yes,
I created a C++ project in VS and link the library, the include header, and the raylib.dll as well, then it worked.
Thanks so much!

**Comment by RobLoach** [comment]
Glad it worked! You wouldn't mind sharing the project files, would you? I would love to grow the Project directory here for examples.

**Comment by sbgssol** [comment]
Ya, I'll do it soon

**Comment by MirrasHue** [comment]
Any news on this? I'm looking forward to try raylib, and now that I saw the comparison between the c++ bindings and c's, this oop aproach looks so much better and make more sense for me. I'll probably use it with codeblocks. Thanks, I appreciate your work.

**Comment by RobLoach** [comment]
Added some more documentation in the README.md. I don't have Visual Studio, so won't be able to make a good project for it.

@sbgssol If you share your project files, I'd be more than happy to copy them in! Would help others like @MirrasHue  :+1:

**Comment by sbgssol** [comment]
Hi, I am very sorry for my late response,
I just found that it's easier to use raylib with Visual Studio when installing raylib through vcpkg, then we just need to import it like others: #include <raylib.h>
FYI @MirrasHue

**Comment by sbgssol** [comment]
> Added some more documentation in the README.md. I don't have Visual Studio, so won't be able to make a good project for it.
> 
> @sbgssol If you share your project files, I'd be more than happy to copy them in! Would help others like @MirrasHue 👍

**Comment by MirrasHue** [comment]
@sbgssol oh, thanks.

**Comment by RobLoach** [comment]
@sbgssol Would you mind sharing your sample project???? Would love to have it as a starter example in here:
https://github.com/RobLoach/raylib-cpp/tree/master/projects
