### ISSUE TITLE
Sharing my own projects built with raylib + raylib-cpp

### ISSUE THREAD

**Issue by ianpan870102** [RobLoach/raylib-cpp#75]
@RobLoach Hi Rob, I heard from another issue thread that you are looking to expand the example projects. I organized a repo of a couple of small games I built with raylib + raylib-cpp [here](https://github.com/ianpan870102/raylib-practices/tree/master/src). Hope this helps some of the beginners when they try to adopt your awesome OOP wrapper and need more guidelines! 

P.s. I'm most proud of my **flappy_bird.cpp** :) The README of my repo contains some screenshots of the gameplay as well!

**Comment by ianpan870102** [comment]
Friendly ping :)

**Comment by RobLoach** [comment]
Wow!!! Impressive library!

**Comment by RobLoach** [comment]
I'm glad you want to share it :+1: .... How's this? https://github.com/RobLoach/raylib-cpp/pull/84

**Comment by RobLoach** [comment]
OOooh, also note that I had removed the static Color variables, like `raylib::Color::Black` https://github.com/RobLoach/raylib-cpp/pull/79

**Comment by ianpan870102** [comment]
> OOooh, also note that I had removed the static Color variables

Right, I'll fix the static Color variables in my repo as soon as I'm free :)
