### ISSUE TITLE
'raylib::Texture2D::Load': must return a value	Texture2D.hpp

### ISSUE THREAD

**Issue by joseph-montanez** [RobLoach/raylib-cpp#8]
I am using Visual Studio and get the following error when loading textures. There are two methods that are to return a boolean but are void.

https://github.com/RobLoach/raylib-cpp/blob/7d866d9f351a280ab4583caf7e696952dee34b6c/include/raylib/Texture2D.hpp#L52

https://github.com/RobLoach/raylib-cpp/blob/7d866d9f351a280ab4583caf7e696952dee34b6c/include/raylib/Texture2D.hpp#L55

Images.hpp has this issue too with LoadPro and loadRaw

**Comment by RobLoach** [comment]
Thanks! Added some compilation options to highlight these too :+1:
