### ISSUE TITLE
Raylib C++ Starter Project Template

### ISSUE THREAD

**Issue by J-Mo63** [RobLoach/raylib-cpp#87]
Hi @RobLoach!

My name is Jonathan and I’ve been working with a mate recently to put together an automated template project for using the C++ bindings with just Make, keeping as much as possible statically linked (you can check it out [here](https://github.com/CapsCollective/raylib-cpp-starter)).

We built the project because we felt like it simplified the setup process, and makes using C++ with raylib far more accessible and understandable for newer devs. As such we thought that it may be of value to mention its existence in this repo, under the "starter projects” section.

If that's cool with you, let me know (if you want, I can throw a PR your way with the changes).

**Comment by EricBarrett** [comment]
This is great! I was having trouble getting everything working on Windows (see: https://github.com/RobLoach/raylib-cpp/issues/89) but I just used this and everything worked fine! Thank you

**Comment by RobLoach** [comment]
THis is excellent! Didn't see this ping before. Got two ideas of where we could point to it from here...

1. In the README.md
2. `projects/Make/README.md`

**Comment by J-Mo63** [comment]
PR #90 looks great @RobLoach - just would change the instructions to say "Linux & macOS" to be a bit more clear. Otherwise happy for you to merge in what you have there, and thank you!

**Comment by J-Mo63** [comment]
> This is great! I was having trouble getting everything working on Windows (see: #89) but I just used this and everything worked fine! Thank you

That's amazing to hear @EricBarrett, we're very glad someone is getting value out of it! Your specific issue (which we also struggled with) was a major reason as to why we decided to create the project in the first place (and I guess that's kind how open source software happens).
