### ISSUE TITLE
SIGABRT in Mesh::Unload() - MacOS,Apple Silicon M1

### ISSUE THREAD

**Issue by stephenaa** [RobLoach/raylib-cpp#98]
I have some code being virtually a port of the raylib  "cubicmap"  sample. When the program exits it experience a SIGABRT in Mesh::Unload().

I might have missed something, this is the core of the code:
 
raylib::Image imMap("resources/cubicmap.png");
raylib::Texture2D cubicmap(imMap);
raylib::Mesh mesh = raylib::Mesh::Cubicmap(imMap, (Vector3){ 1.0f, 1.0f, 1.0f });
raylib::Model model(mesh);
...

The original pure C ray lib example based code worked fine, on the other hand - not as much cleanup is done as is being done with the destructors being called.

Any help in tracing this down is appreciated

/Stephen

**Comment by RobLoach** [comment]
Thanks for posting this! Definitely want to track those down. I'll see if I can push up a pull request so we can test further.

**Comment by RobLoach** [comment]
Which example did you use?

**Comment by stephenaa** [comment]
int main(void)
    {
    // Initialization
    //--------------------------------------------------------------------------------------
    const int screenWidth = 800;
    const int screenHeight = 450;
    
    raylib::Window w(screenWidth, screenHeight, "raylib-cpp - basic window");
    raylib::Texture logo("raylib_logo.png");
    
    // Define the camera to look into our 3d world
    raylib::Camera camera = { { 0.2f, 0.4f, 0.2f }, { 0.0f, 0.0f, 0.0f }, { 0.0f, 1.0f, 0.0f }, 45.0f, 0 };
    
    
    raylib::Image imMap("resources/cubicmap.png");
    raylib::Texture2D cubicmap(imMap);
    
    raylib::Mesh mesh = raylib::Mesh::Cubicmap(imMap, (Vector3){ 1.0f, 1.0f, 1.0f });
    raylib::Model model(mesh);
    
    // NOTE: By default each cube is mapped to one part of texture atlas
    raylib::Texture2D texture ("resources/cubicmap_atlas.png");    // Load map texture
    model.materials[0].maps[MAP_DIFFUSE].texture = texture;        // Set map diffuse texture
    
    // Get map image data to be used for collision detection
    raylib::Color *mapPixels = (raylib::Color*)LoadImageColors(imMap);
    imMap.Unload();
    
    raylib::Vector3 mapPosition (-16.0f, 0.0f, -8.0f );  // Set model position
    
    camera.SetMode(CAMERA_FIRST_PERSON);     // Set camera mode
    
    raylib::Vector3 enemySpherePos (-0.0f, 0.5f, -0.5f );
    float enemySphereSize = 0.5f;

    float enemySpeedX = 0.01f;
    float enemySpeedZ = 0.01f;
    
    SetTargetFPS(60);
    while (!w.ShouldClose())
    {
        // Update
        //----------------------------------------------------------------------------------
        enemySpherePos.x += enemySpeedX;
        enemySpherePos.z += enemySpeedZ;
        
        raylib::Vector3 oldCamPos = camera.position;    // Store old camera position
        camera.Update();

        // Check player collision (we simplify to 2D collision detection)
        raylib::Vector2 playerPos = { camera.position.x, camera.position.z };
        float playerRadius = 0.1f;  // Collision radius (player is modelled as a cilinder for collision)
      
        // Check map collisions using image data and player position
        if ( mapCollision(playerPos, playerRadius, cubicmap, mapPosition, mapPixels) )
        {
            camera.position = oldCamPos;
        }
        
        raylib::Vector2 enemyPos = {enemySpherePos.x, enemySpherePos.z};
        if ( mapCollision(enemyPos, enemySphereSize, cubicmap, mapPosition, mapPixels) )
        {
            enemySpherePos.x = enemyPos.x;
            enemySpherePos.z = enemyPos.y;
        }

        
        //----------------------------------------------------------------------------------
        // Draw
        BeginDrawing();

        ClearBackground(RAYWHITE);
        DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
        
        BeginMode3D(camera);
        
        DrawModel(model, mapPosition, 1.0f, WHITE);                     // Draw maze map
        
        // "Draw enemy-sphere"
        DrawSphere(enemySpherePos, enemySphereSize, GOLD);
        DrawSphereWires(enemySpherePos, enemySphereSize, 16, 16, GOLD);
        
        EndMode3D();
        
        DrawText(TextFormat("PlayerPos: %f, %f", playerPos.x,playerPos.y), 200, 80, 20, RED);
        DrawText(TextFormat("mapPosition: %f, %f, %f", mapPosition.x, mapPosition.y ,mapPosition.z), 200, 100, 20, RED);
        
        DrawFPS(10, 10);

        EndDrawing();
    }
    
    return 0;
    }

**Comment by stephenaa** [comment]
That is the modified example. Not much really. I might be blind on an error I am doing, but it is not obvious to me what I might be doing wrong.

**Comment by RobLoach** [comment]
@stephenaa Thanks... Had a hack at implementing models_first_person_maze to debug. Added a few checks before unloading the objects. Looks like the Model possibly unloads the Mesh, so then when the Mesh tries to Unload, it is already freed, so ends up failing.

**Comment by RobLoach** [comment]
The other thing we might be able to do is have `raylib::Mesh::Cubicmap` return the struct object `::Mesh` instead of the raylib-cpp class `raylib::Mesh`.

```
Mesh mesh = raylib::Mesh::Cubicmap(imMap, (Vector3){ 1.0f, 1.0f, 1.0f });
```

That way it wouldn't do the unload on you.

**Comment by RobLoach** [comment]
Pushed that change up in the Pull Request over at https://github.com/RobLoach/raylib-cpp/pull/99 . Thinking of pushing this one forwards.

Thanks for the find, @stephenaa! You will have to pull the latest once it's merged, and update to use...

```
Mesh mesh = raylib::Mesh::Cubicmap(imMap, (Vector3){ 1.0f, 1.0f, 1.0f });
```

**Comment by stephenaa** [comment]
Verified that it fixes the SIGABRT I saw. Sorry for the delay, I'm in CET time :-)

**Comment by RobLoach** [comment]
Thanks so much for debugging! Merged.
